packages:
  - apps/*
  - packages/*

catalog:
  '@ag-ui/client': ^0.0.53
  '@copilotkit/react-core': ^1.57.1
  '@copilotkit/react-ui': ^1.57.1
  '@copilotkit/runtime': ^1.57.1
  '@copilotkit/runtime-client-gql': ^1.51.1
  '@prisma/client': ^7.2.0
  '@tanstack/react-router': ^1.141.1
  '@types/node': ^22.13.14
  '@types/qs': ^6.14.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  ai: ^6.0.3
  alchemy: ^0.90.0
  axios: ^1.13.2
  dotenv: ^17.2.2
  lucide-react: ^0.546.0
  next-themes: ^0.4.6
  qs: ^6.14.1
  react: ^19.2.3
  react-dom: ^19.2.3
  sonner: ^2.0.5
  tailwindcss: ^4.1.18
  zod: ^4.1.13

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@prisma/engines'
  - esbuild
  - msw
  - prisma
  - workerd

onlyBuiltDependencies:
  - '@scarf/scarf'
  - bcrypt
  - grpc-tools
  - protobufjs
  - sharp
