/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedGENERALRepairCasesManagementRouteRouteImport } from './routes/_authenticated/(GENERAL)/repair-cases-management/route'
import { Route as AuthenticatedAiGeminiIndexRouteImport } from './routes/_authenticated/ai/gemini/index'
import { Route as AuthenticatedAiExampleIndexRouteImport } from './routes/_authenticated/ai/example/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/index'
import { Route as AuthenticatedSETTINGSSettingsIndexRouteImport } from './routes/_authenticated/(SETTINGS)/settings/index'
import { Route as AuthenticatedSETTINGSHelpCenterIndexRouteImport } from './routes/_authenticated/(SETTINGS)/help-center/index'
import { Route as AuthenticatedREPORTSWeeklyReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/weekly-report/index'
import { Route as AuthenticatedREPORTSPurchaseLocationErrorReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/purchase-location-error-report/index'
import { Route as AuthenticatedREPORTSPscCostReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/psc-cost-report/index'
import { Route as AuthenticatedREPORTSPaymentReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/payment-report/index'
import { Route as AuthenticatedREPORTSOutOfWarrantyReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/out-of-warranty-report/index'
import { Route as AuthenticatedREPORTSModelErrorReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/model-error-report/index'
import { Route as AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRouteImport } from './routes/_authenticated/(REPORTS)/history-of-repair-cases-status-changes/index'
import { Route as AuthenticatedREPORTSCostReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/cost-report/index'
import { Route as AuthenticatedREPORTSCategoryErrorReportIndexRouteImport } from './routes/_authenticated/(REPORTS)/category-error-report/index'
import { Route as AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRouteImport } from './routes/_authenticated/(REPORTS)/accessories-status-statistics/index'
import { Route as AuthenticatedGENERALRepairCasesManagementIndexRouteImport } from './routes/_authenticated/(GENERAL)/repair-cases-management/index'
import { Route as AuthenticatedGENERALPaymentPendingRepairCasesIndexRouteImport } from './routes/_authenticated/(GENERAL)/payment-pending-repair-cases/index'
import { Route as AuthenticatedGENERALRepairCasesManagementIdRouteImport } from './routes/_authenticated/(GENERAL)/repair-cases-management/$id'
import { Route as AuthenticatedSETTINGSSettingsNotificationsIndexRouteImport } from './routes/_authenticated/(SETTINGS)/settings/notifications/index'
import { Route as AuthenticatedSETTINGSSettingsDisplayIndexRouteImport } from './routes/_authenticated/(SETTINGS)/settings/display/index'
import { Route as AuthenticatedSETTINGSSettingsAppearanceIndexRouteImport } from './routes/_authenticated/(SETTINGS)/settings/appearance/index'
import { Route as AuthenticatedSETTINGSSettingsAccountIndexRouteImport } from './routes/_authenticated/(SETTINGS)/settings/account/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedGENERALRepairCasesManagementRouteRoute =
  AuthenticatedGENERALRepairCasesManagementRouteRouteImport.update({
    id: '/(GENERAL)/repair-cases-management',
    path: '/repair-cases-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiGeminiIndexRoute =
  AuthenticatedAiGeminiIndexRouteImport.update({
    id: '/ai/gemini/',
    path: '/ai/gemini/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiExampleIndexRoute =
  AuthenticatedAiExampleIndexRouteImport.update({
    id: '/ai/example/',
    path: '/ai/example/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/user-management/',
    path: '/user-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/roles-management/',
    path: '/roles-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/reference-documents-management/',
      path: '/reference-documents-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/reference-documentation/',
      path: '/reference-documentation/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/purchase-locations-management/',
      path: '/purchase-locations-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/products-management/',
    path: '/products-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/product-categories-management/',
      path: '/product-categories-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/permissions-management/',
      path: '/permissions-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/customer-management/',
    path: '/customer-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/central-warehouse-management/',
      path: '/central-warehouse-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/asc-centers-management/',
    path: '/asc-centers-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/accessories-management/',
      path: '/accessories-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSETTINGSSettingsIndexRoute =
  AuthenticatedSETTINGSSettingsIndexRouteImport.update({
    id: '/(SETTINGS)/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSETTINGSHelpCenterIndexRoute =
  AuthenticatedSETTINGSHelpCenterIndexRouteImport.update({
    id: '/(SETTINGS)/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSWeeklyReportIndexRoute =
  AuthenticatedREPORTSWeeklyReportIndexRouteImport.update({
    id: '/(REPORTS)/weekly-report/',
    path: '/weekly-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute =
  AuthenticatedREPORTSPurchaseLocationErrorReportIndexRouteImport.update({
    id: '/(REPORTS)/purchase-location-error-report/',
    path: '/purchase-location-error-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSPscCostReportIndexRoute =
  AuthenticatedREPORTSPscCostReportIndexRouteImport.update({
    id: '/(REPORTS)/psc-cost-report/',
    path: '/psc-cost-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSPaymentReportIndexRoute =
  AuthenticatedREPORTSPaymentReportIndexRouteImport.update({
    id: '/(REPORTS)/payment-report/',
    path: '/payment-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSOutOfWarrantyReportIndexRoute =
  AuthenticatedREPORTSOutOfWarrantyReportIndexRouteImport.update({
    id: '/(REPORTS)/out-of-warranty-report/',
    path: '/out-of-warranty-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSModelErrorReportIndexRoute =
  AuthenticatedREPORTSModelErrorReportIndexRouteImport.update({
    id: '/(REPORTS)/model-error-report/',
    path: '/model-error-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute =
  AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRouteImport.update({
    id: '/(REPORTS)/history-of-repair-cases-status-changes/',
    path: '/history-of-repair-cases-status-changes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSCostReportIndexRoute =
  AuthenticatedREPORTSCostReportIndexRouteImport.update({
    id: '/(REPORTS)/cost-report/',
    path: '/cost-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSCategoryErrorReportIndexRoute =
  AuthenticatedREPORTSCategoryErrorReportIndexRouteImport.update({
    id: '/(REPORTS)/category-error-report/',
    path: '/category-error-report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute =
  AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRouteImport.update({
    id: '/(REPORTS)/accessories-status-statistics/',
    path: '/accessories-status-statistics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGENERALRepairCasesManagementIndexRoute =
  AuthenticatedGENERALRepairCasesManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGENERALRepairCasesManagementRouteRoute,
  } as any)
const AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute =
  AuthenticatedGENERALPaymentPendingRepairCasesIndexRouteImport.update({
    id: '/(GENERAL)/payment-pending-repair-cases/',
    path: '/payment-pending-repair-cases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGENERALRepairCasesManagementIdRoute =
  AuthenticatedGENERALRepairCasesManagementIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedGENERALRepairCasesManagementRouteRoute,
  } as any)
const AuthenticatedSETTINGSSettingsNotificationsIndexRoute =
  AuthenticatedSETTINGSSettingsNotificationsIndexRouteImport.update({
    id: '/(SETTINGS)/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSETTINGSSettingsDisplayIndexRoute =
  AuthenticatedSETTINGSSettingsDisplayIndexRouteImport.update({
    id: '/(SETTINGS)/settings/display/',
    path: '/settings/display/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSETTINGSSettingsAppearanceIndexRoute =
  AuthenticatedSETTINGSSettingsAppearanceIndexRouteImport.update({
    id: '/(SETTINGS)/settings/appearance/',
    path: '/settings/appearance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSETTINGSSettingsAccountIndexRoute =
  AuthenticatedSETTINGSSettingsAccountIndexRouteImport.update({
    id: '/(SETTINGS)/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/repair-cases-management': typeof AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren
  '/repair-cases-management/$id': typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  '/payment-pending-repair-cases/': typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  '/repair-cases-management/': typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
  '/accessories-status-statistics/': typeof AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute
  '/category-error-report/': typeof AuthenticatedREPORTSCategoryErrorReportIndexRoute
  '/cost-report/': typeof AuthenticatedREPORTSCostReportIndexRoute
  '/history-of-repair-cases-status-changes/': typeof AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute
  '/model-error-report/': typeof AuthenticatedREPORTSModelErrorReportIndexRoute
  '/out-of-warranty-report/': typeof AuthenticatedREPORTSOutOfWarrantyReportIndexRoute
  '/payment-report/': typeof AuthenticatedREPORTSPaymentReportIndexRoute
  '/psc-cost-report/': typeof AuthenticatedREPORTSPscCostReportIndexRoute
  '/purchase-location-error-report/': typeof AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute
  '/weekly-report/': typeof AuthenticatedREPORTSWeeklyReportIndexRoute
  '/help-center/': typeof AuthenticatedSETTINGSHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSETTINGSSettingsIndexRoute
  '/accessories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  '/asc-centers-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  '/central-warehouse-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  '/customer-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  '/permissions-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  '/product-categories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  '/products-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  '/purchase-locations-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  '/reference-documentation/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  '/reference-documents-management/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  '/roles-management/': typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  '/user-management/': typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  '/ai/example/': typeof AuthenticatedAiExampleIndexRoute
  '/ai/gemini/': typeof AuthenticatedAiGeminiIndexRoute
  '/settings/account/': typeof AuthenticatedSETTINGSSettingsAccountIndexRoute
  '/settings/appearance/': typeof AuthenticatedSETTINGSSettingsAppearanceIndexRoute
  '/settings/display/': typeof AuthenticatedSETTINGSSettingsDisplayIndexRoute
  '/settings/notifications/': typeof AuthenticatedSETTINGSSettingsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof AuthenticatedIndexRoute
  '/repair-cases-management/$id': typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  '/payment-pending-repair-cases': typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  '/repair-cases-management': typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
  '/accessories-status-statistics': typeof AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute
  '/category-error-report': typeof AuthenticatedREPORTSCategoryErrorReportIndexRoute
  '/cost-report': typeof AuthenticatedREPORTSCostReportIndexRoute
  '/history-of-repair-cases-status-changes': typeof AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute
  '/model-error-report': typeof AuthenticatedREPORTSModelErrorReportIndexRoute
  '/out-of-warranty-report': typeof AuthenticatedREPORTSOutOfWarrantyReportIndexRoute
  '/payment-report': typeof AuthenticatedREPORTSPaymentReportIndexRoute
  '/psc-cost-report': typeof AuthenticatedREPORTSPscCostReportIndexRoute
  '/purchase-location-error-report': typeof AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute
  '/weekly-report': typeof AuthenticatedREPORTSWeeklyReportIndexRoute
  '/help-center': typeof AuthenticatedSETTINGSHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSETTINGSSettingsIndexRoute
  '/accessories-management': typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  '/asc-centers-management': typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  '/central-warehouse-management': typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  '/customer-management': typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  '/permissions-management': typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  '/product-categories-management': typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  '/products-management': typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  '/purchase-locations-management': typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  '/reference-documentation': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  '/reference-documents-management': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  '/roles-management': typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  '/user-management': typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  '/ai/example': typeof AuthenticatedAiExampleIndexRoute
  '/ai/gemini': typeof AuthenticatedAiGeminiIndexRoute
  '/settings/account': typeof AuthenticatedSETTINGSSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedSETTINGSSettingsAppearanceIndexRoute
  '/settings/display': typeof AuthenticatedSETTINGSSettingsDisplayIndexRoute
  '/settings/notifications': typeof AuthenticatedSETTINGSSettingsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/(GENERAL)/repair-cases-management': typeof AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren
  '/_authenticated/(GENERAL)/repair-cases-management/$id': typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  '/_authenticated/(GENERAL)/payment-pending-repair-cases/': typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  '/_authenticated/(GENERAL)/repair-cases-management/': typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
  '/_authenticated/(REPORTS)/accessories-status-statistics/': typeof AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute
  '/_authenticated/(REPORTS)/category-error-report/': typeof AuthenticatedREPORTSCategoryErrorReportIndexRoute
  '/_authenticated/(REPORTS)/cost-report/': typeof AuthenticatedREPORTSCostReportIndexRoute
  '/_authenticated/(REPORTS)/history-of-repair-cases-status-changes/': typeof AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute
  '/_authenticated/(REPORTS)/model-error-report/': typeof AuthenticatedREPORTSModelErrorReportIndexRoute
  '/_authenticated/(REPORTS)/out-of-warranty-report/': typeof AuthenticatedREPORTSOutOfWarrantyReportIndexRoute
  '/_authenticated/(REPORTS)/payment-report/': typeof AuthenticatedREPORTSPaymentReportIndexRoute
  '/_authenticated/(REPORTS)/psc-cost-report/': typeof AuthenticatedREPORTSPscCostReportIndexRoute
  '/_authenticated/(REPORTS)/purchase-location-error-report/': typeof AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute
  '/_authenticated/(REPORTS)/weekly-report/': typeof AuthenticatedREPORTSWeeklyReportIndexRoute
  '/_authenticated/(SETTINGS)/help-center/': typeof AuthenticatedSETTINGSHelpCenterIndexRoute
  '/_authenticated/(SETTINGS)/settings/': typeof AuthenticatedSETTINGSSettingsIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/': typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/': typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  '/_authenticated/ai/example/': typeof AuthenticatedAiExampleIndexRoute
  '/_authenticated/ai/gemini/': typeof AuthenticatedAiGeminiIndexRoute
  '/_authenticated/(SETTINGS)/settings/account/': typeof AuthenticatedSETTINGSSettingsAccountIndexRoute
  '/_authenticated/(SETTINGS)/settings/appearance/': typeof AuthenticatedSETTINGSSettingsAppearanceIndexRoute
  '/_authenticated/(SETTINGS)/settings/display/': typeof AuthenticatedSETTINGSSettingsDisplayIndexRoute
  '/_authenticated/(SETTINGS)/settings/notifications/': typeof AuthenticatedSETTINGSSettingsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/repair-cases-management'
    | '/repair-cases-management/$id'
    | '/payment-pending-repair-cases/'
    | '/repair-cases-management/'
    | '/accessories-status-statistics/'
    | '/category-error-report/'
    | '/cost-report/'
    | '/history-of-repair-cases-status-changes/'
    | '/model-error-report/'
    | '/out-of-warranty-report/'
    | '/payment-report/'
    | '/psc-cost-report/'
    | '/purchase-location-error-report/'
    | '/weekly-report/'
    | '/help-center/'
    | '/settings/'
    | '/accessories-management/'
    | '/asc-centers-management/'
    | '/central-warehouse-management/'
    | '/customer-management/'
    | '/permissions-management/'
    | '/product-categories-management/'
    | '/products-management/'
    | '/purchase-locations-management/'
    | '/reference-documentation/'
    | '/reference-documents-management/'
    | '/roles-management/'
    | '/user-management/'
    | '/ai/example/'
    | '/ai/gemini/'
    | '/settings/account/'
    | '/settings/appearance/'
    | '/settings/display/'
    | '/settings/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/repair-cases-management/$id'
    | '/payment-pending-repair-cases'
    | '/repair-cases-management'
    | '/accessories-status-statistics'
    | '/category-error-report'
    | '/cost-report'
    | '/history-of-repair-cases-status-changes'
    | '/model-error-report'
    | '/out-of-warranty-report'
    | '/payment-report'
    | '/psc-cost-report'
    | '/purchase-location-error-report'
    | '/weekly-report'
    | '/help-center'
    | '/settings'
    | '/accessories-management'
    | '/asc-centers-management'
    | '/central-warehouse-management'
    | '/customer-management'
    | '/permissions-management'
    | '/product-categories-management'
    | '/products-management'
    | '/purchase-locations-management'
    | '/reference-documentation'
    | '/reference-documents-management'
    | '/roles-management'
    | '/user-management'
    | '/ai/example'
    | '/ai/gemini'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_authenticated/'
    | '/_authenticated/(GENERAL)/repair-cases-management'
    | '/_authenticated/(GENERAL)/repair-cases-management/$id'
    | '/_authenticated/(GENERAL)/payment-pending-repair-cases/'
    | '/_authenticated/(GENERAL)/repair-cases-management/'
    | '/_authenticated/(REPORTS)/accessories-status-statistics/'
    | '/_authenticated/(REPORTS)/category-error-report/'
    | '/_authenticated/(REPORTS)/cost-report/'
    | '/_authenticated/(REPORTS)/history-of-repair-cases-status-changes/'
    | '/_authenticated/(REPORTS)/model-error-report/'
    | '/_authenticated/(REPORTS)/out-of-warranty-report/'
    | '/_authenticated/(REPORTS)/payment-report/'
    | '/_authenticated/(REPORTS)/psc-cost-report/'
    | '/_authenticated/(REPORTS)/purchase-location-error-report/'
    | '/_authenticated/(REPORTS)/weekly-report/'
    | '/_authenticated/(SETTINGS)/help-center/'
    | '/_authenticated/(SETTINGS)/settings/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/'
    | '/_authenticated/ai/example/'
    | '/_authenticated/ai/gemini/'
    | '/_authenticated/(SETTINGS)/settings/account/'
    | '/_authenticated/(SETTINGS)/settings/appearance/'
    | '/_authenticated/(SETTINGS)/settings/display/'
    | '/_authenticated/(SETTINGS)/settings/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/(GENERAL)/repair-cases-management': {
      id: '/_authenticated/(GENERAL)/repair-cases-management'
      path: '/repair-cases-management'
      fullPath: '/repair-cases-management'
      preLoaderRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/gemini/': {
      id: '/_authenticated/ai/gemini/'
      path: '/ai/gemini'
      fullPath: '/ai/gemini/'
      preLoaderRoute: typeof AuthenticatedAiGeminiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/example/': {
      id: '/_authenticated/ai/example/'
      path: '/ai/example'
      fullPath: '/ai/example/'
      preLoaderRoute: typeof AuthenticatedAiExampleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/'
      path: '/roles-management'
      fullPath: '/roles-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/'
      path: '/reference-documents-management'
      fullPath: '/reference-documents-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/'
      path: '/reference-documentation'
      fullPath: '/reference-documentation/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/'
      path: '/purchase-locations-management'
      fullPath: '/purchase-locations-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/'
      path: '/products-management'
      fullPath: '/products-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/'
      path: '/product-categories-management'
      fullPath: '/product-categories-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/'
      path: '/permissions-management'
      fullPath: '/permissions-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/'
      path: '/customer-management'
      fullPath: '/customer-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/'
      path: '/central-warehouse-management'
      fullPath: '/central-warehouse-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/'
      path: '/asc-centers-management'
      fullPath: '/asc-centers-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/'
      path: '/accessories-management'
      fullPath: '/accessories-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SETTINGS)/settings/': {
      id: '/_authenticated/(SETTINGS)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSETTINGSSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SETTINGS)/help-center/': {
      id: '/_authenticated/(SETTINGS)/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedSETTINGSHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/weekly-report/': {
      id: '/_authenticated/(REPORTS)/weekly-report/'
      path: '/weekly-report'
      fullPath: '/weekly-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSWeeklyReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/purchase-location-error-report/': {
      id: '/_authenticated/(REPORTS)/purchase-location-error-report/'
      path: '/purchase-location-error-report'
      fullPath: '/purchase-location-error-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSPurchaseLocationErrorReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/psc-cost-report/': {
      id: '/_authenticated/(REPORTS)/psc-cost-report/'
      path: '/psc-cost-report'
      fullPath: '/psc-cost-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSPscCostReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/payment-report/': {
      id: '/_authenticated/(REPORTS)/payment-report/'
      path: '/payment-report'
      fullPath: '/payment-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSPaymentReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/out-of-warranty-report/': {
      id: '/_authenticated/(REPORTS)/out-of-warranty-report/'
      path: '/out-of-warranty-report'
      fullPath: '/out-of-warranty-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSOutOfWarrantyReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/model-error-report/': {
      id: '/_authenticated/(REPORTS)/model-error-report/'
      path: '/model-error-report'
      fullPath: '/model-error-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSModelErrorReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/history-of-repair-cases-status-changes/': {
      id: '/_authenticated/(REPORTS)/history-of-repair-cases-status-changes/'
      path: '/history-of-repair-cases-status-changes'
      fullPath: '/history-of-repair-cases-status-changes/'
      preLoaderRoute: typeof AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/cost-report/': {
      id: '/_authenticated/(REPORTS)/cost-report/'
      path: '/cost-report'
      fullPath: '/cost-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSCostReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/category-error-report/': {
      id: '/_authenticated/(REPORTS)/category-error-report/'
      path: '/category-error-report'
      fullPath: '/category-error-report/'
      preLoaderRoute: typeof AuthenticatedREPORTSCategoryErrorReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(REPORTS)/accessories-status-statistics/': {
      id: '/_authenticated/(REPORTS)/accessories-status-statistics/'
      path: '/accessories-status-statistics'
      fullPath: '/accessories-status-statistics/'
      preLoaderRoute: typeof AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(GENERAL)/repair-cases-management/': {
      id: '/_authenticated/(GENERAL)/repair-cases-management/'
      path: '/'
      fullPath: '/repair-cases-management/'
      preLoaderRoute: typeof AuthenticatedGENERALRepairCasesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRoute
    }
    '/_authenticated/(GENERAL)/payment-pending-repair-cases/': {
      id: '/_authenticated/(GENERAL)/payment-pending-repair-cases/'
      path: '/payment-pending-repair-cases'
      fullPath: '/payment-pending-repair-cases/'
      preLoaderRoute: typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(GENERAL)/repair-cases-management/$id': {
      id: '/_authenticated/(GENERAL)/repair-cases-management/$id'
      path: '/$id'
      fullPath: '/repair-cases-management/$id'
      preLoaderRoute: typeof AuthenticatedGENERALRepairCasesManagementIdRouteImport
      parentRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRoute
    }
    '/_authenticated/(SETTINGS)/settings/notifications/': {
      id: '/_authenticated/(SETTINGS)/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof AuthenticatedSETTINGSSettingsNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SETTINGS)/settings/display/': {
      id: '/_authenticated/(SETTINGS)/settings/display/'
      path: '/settings/display'
      fullPath: '/settings/display/'
      preLoaderRoute: typeof AuthenticatedSETTINGSSettingsDisplayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SETTINGS)/settings/appearance/': {
      id: '/_authenticated/(SETTINGS)/settings/appearance/'
      path: '/settings/appearance'
      fullPath: '/settings/appearance/'
      preLoaderRoute: typeof AuthenticatedSETTINGSSettingsAppearanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SETTINGS)/settings/account/': {
      id: '/_authenticated/(SETTINGS)/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof AuthenticatedSETTINGSSettingsAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedGENERALRepairCasesManagementRouteRouteChildren {
  AuthenticatedGENERALRepairCasesManagementIdRoute: typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  AuthenticatedGENERALRepairCasesManagementIndexRoute: typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
}

const AuthenticatedGENERALRepairCasesManagementRouteRouteChildren: AuthenticatedGENERALRepairCasesManagementRouteRouteChildren =
  {
    AuthenticatedGENERALRepairCasesManagementIdRoute:
      AuthenticatedGENERALRepairCasesManagementIdRoute,
    AuthenticatedGENERALRepairCasesManagementIndexRoute:
      AuthenticatedGENERALRepairCasesManagementIndexRoute,
  }

const AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren =
  AuthenticatedGENERALRepairCasesManagementRouteRoute._addFileChildren(
    AuthenticatedGENERALRepairCasesManagementRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGENERALRepairCasesManagementRouteRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren
  AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute: typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute: typeof AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute
  AuthenticatedREPORTSCategoryErrorReportIndexRoute: typeof AuthenticatedREPORTSCategoryErrorReportIndexRoute
  AuthenticatedREPORTSCostReportIndexRoute: typeof AuthenticatedREPORTSCostReportIndexRoute
  AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute: typeof AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute
  AuthenticatedREPORTSModelErrorReportIndexRoute: typeof AuthenticatedREPORTSModelErrorReportIndexRoute
  AuthenticatedREPORTSOutOfWarrantyReportIndexRoute: typeof AuthenticatedREPORTSOutOfWarrantyReportIndexRoute
  AuthenticatedREPORTSPaymentReportIndexRoute: typeof AuthenticatedREPORTSPaymentReportIndexRoute
  AuthenticatedREPORTSPscCostReportIndexRoute: typeof AuthenticatedREPORTSPscCostReportIndexRoute
  AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute: typeof AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute
  AuthenticatedREPORTSWeeklyReportIndexRoute: typeof AuthenticatedREPORTSWeeklyReportIndexRoute
  AuthenticatedSETTINGSHelpCenterIndexRoute: typeof AuthenticatedSETTINGSHelpCenterIndexRoute
  AuthenticatedSETTINGSSettingsIndexRoute: typeof AuthenticatedSETTINGSSettingsIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  AuthenticatedAiExampleIndexRoute: typeof AuthenticatedAiExampleIndexRoute
  AuthenticatedAiGeminiIndexRoute: typeof AuthenticatedAiGeminiIndexRoute
  AuthenticatedSETTINGSSettingsAccountIndexRoute: typeof AuthenticatedSETTINGSSettingsAccountIndexRoute
  AuthenticatedSETTINGSSettingsAppearanceIndexRoute: typeof AuthenticatedSETTINGSSettingsAppearanceIndexRoute
  AuthenticatedSETTINGSSettingsDisplayIndexRoute: typeof AuthenticatedSETTINGSSettingsDisplayIndexRoute
  AuthenticatedSETTINGSSettingsNotificationsIndexRoute: typeof AuthenticatedSETTINGSSettingsNotificationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGENERALRepairCasesManagementRouteRoute:
    AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren,
  AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute:
    AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute,
  AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute:
    AuthenticatedREPORTSAccessoriesStatusStatisticsIndexRoute,
  AuthenticatedREPORTSCategoryErrorReportIndexRoute:
    AuthenticatedREPORTSCategoryErrorReportIndexRoute,
  AuthenticatedREPORTSCostReportIndexRoute:
    AuthenticatedREPORTSCostReportIndexRoute,
  AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute:
    AuthenticatedREPORTSHistoryOfRepairCasesStatusChangesIndexRoute,
  AuthenticatedREPORTSModelErrorReportIndexRoute:
    AuthenticatedREPORTSModelErrorReportIndexRoute,
  AuthenticatedREPORTSOutOfWarrantyReportIndexRoute:
    AuthenticatedREPORTSOutOfWarrantyReportIndexRoute,
  AuthenticatedREPORTSPaymentReportIndexRoute:
    AuthenticatedREPORTSPaymentReportIndexRoute,
  AuthenticatedREPORTSPscCostReportIndexRoute:
    AuthenticatedREPORTSPscCostReportIndexRoute,
  AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute:
    AuthenticatedREPORTSPurchaseLocationErrorReportIndexRoute,
  AuthenticatedREPORTSWeeklyReportIndexRoute:
    AuthenticatedREPORTSWeeklyReportIndexRoute,
  AuthenticatedSETTINGSHelpCenterIndexRoute:
    AuthenticatedSETTINGSHelpCenterIndexRoute,
  AuthenticatedSETTINGSSettingsIndexRoute:
    AuthenticatedSETTINGSSettingsIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute,
  AuthenticatedAiExampleIndexRoute: AuthenticatedAiExampleIndexRoute,
  AuthenticatedAiGeminiIndexRoute: AuthenticatedAiGeminiIndexRoute,
  AuthenticatedSETTINGSSettingsAccountIndexRoute:
    AuthenticatedSETTINGSSettingsAccountIndexRoute,
  AuthenticatedSETTINGSSettingsAppearanceIndexRoute:
    AuthenticatedSETTINGSSettingsAppearanceIndexRoute,
  AuthenticatedSETTINGSSettingsDisplayIndexRoute:
    AuthenticatedSETTINGSSettingsDisplayIndexRoute,
  AuthenticatedSETTINGSSettingsNotificationsIndexRoute:
    AuthenticatedSETTINGSSettingsNotificationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
