/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedGENERALRepairCasesManagementRouteRouteImport } from './routes/_authenticated/(GENERAL)/repair-cases-management/route'
import { Route as AuthenticatedAiGeminiIndexRouteImport } from './routes/_authenticated/ai/gemini/index'
import { Route as AuthenticatedAiExampleIndexRouteImport } from './routes/_authenticated/ai/example/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/index'
import { Route as AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRouteImport } from './routes/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/index'
import { Route as AuthenticatedGENERALRepairCasesManagementIndexRouteImport } from './routes/_authenticated/(GENERAL)/repair-cases-management/index'
import { Route as AuthenticatedGENERALPaymentPendingRepairCasesIndexRouteImport } from './routes/_authenticated/(GENERAL)/payment-pending-repair-cases/index'
import { Route as AuthenticatedGENERALRepairCasesManagementIdRouteImport } from './routes/_authenticated/(GENERAL)/repair-cases-management/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedGENERALRepairCasesManagementRouteRoute =
  AuthenticatedGENERALRepairCasesManagementRouteRouteImport.update({
    id: '/(GENERAL)/repair-cases-management',
    path: '/repair-cases-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiGeminiIndexRoute =
  AuthenticatedAiGeminiIndexRouteImport.update({
    id: '/ai/gemini/',
    path: '/ai/gemini/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiExampleIndexRoute =
  AuthenticatedAiExampleIndexRouteImport.update({
    id: '/ai/example/',
    path: '/ai/example/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/user-management/',
    path: '/user-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/roles-management/',
    path: '/roles-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/reference-documents-management/',
      path: '/reference-documents-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/reference-documentation/',
      path: '/reference-documentation/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/purchase-locations-management/',
      path: '/purchase-locations-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/products-management/',
    path: '/products-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/product-categories-management/',
      path: '/product-categories-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/permissions-management/',
      path: '/permissions-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/customer-management/',
    path: '/customer-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/central-warehouse-management/',
      path: '/central-warehouse-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRouteImport.update({
    id: '/(SYSTEM-ADMINISTRATION)/asc-centers-management/',
    path: '/asc-centers-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute =
  AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRouteImport.update(
    {
      id: '/(SYSTEM-ADMINISTRATION)/accessories-management/',
      path: '/accessories-management/',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )
const AuthenticatedGENERALRepairCasesManagementIndexRoute =
  AuthenticatedGENERALRepairCasesManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGENERALRepairCasesManagementRouteRoute,
  } as any)
const AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute =
  AuthenticatedGENERALPaymentPendingRepairCasesIndexRouteImport.update({
    id: '/(GENERAL)/payment-pending-repair-cases/',
    path: '/payment-pending-repair-cases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGENERALRepairCasesManagementIdRoute =
  AuthenticatedGENERALRepairCasesManagementIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedGENERALRepairCasesManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/repair-cases-management': typeof AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren
  '/repair-cases-management/$id': typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  '/payment-pending-repair-cases/': typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  '/repair-cases-management/': typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
  '/accessories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  '/asc-centers-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  '/central-warehouse-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  '/customer-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  '/permissions-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  '/product-categories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  '/products-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  '/purchase-locations-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  '/reference-documentation/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  '/reference-documents-management/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  '/roles-management/': typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  '/user-management/': typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  '/ai/example/': typeof AuthenticatedAiExampleIndexRoute
  '/ai/gemini/': typeof AuthenticatedAiGeminiIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof AuthenticatedIndexRoute
  '/repair-cases-management/$id': typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  '/payment-pending-repair-cases': typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  '/repair-cases-management': typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
  '/accessories-management': typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  '/asc-centers-management': typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  '/central-warehouse-management': typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  '/customer-management': typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  '/permissions-management': typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  '/product-categories-management': typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  '/products-management': typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  '/purchase-locations-management': typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  '/reference-documentation': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  '/reference-documents-management': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  '/roles-management': typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  '/user-management': typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  '/ai/example': typeof AuthenticatedAiExampleIndexRoute
  '/ai/gemini': typeof AuthenticatedAiGeminiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/(GENERAL)/repair-cases-management': typeof AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren
  '/_authenticated/(GENERAL)/repair-cases-management/$id': typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  '/_authenticated/(GENERAL)/payment-pending-repair-cases/': typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  '/_authenticated/(GENERAL)/repair-cases-management/': typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/': typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/': typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/': typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/': typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/': typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/': typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/': typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  '/_authenticated/ai/example/': typeof AuthenticatedAiExampleIndexRoute
  '/_authenticated/ai/gemini/': typeof AuthenticatedAiGeminiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/repair-cases-management'
    | '/repair-cases-management/$id'
    | '/payment-pending-repair-cases/'
    | '/repair-cases-management/'
    | '/accessories-management/'
    | '/asc-centers-management/'
    | '/central-warehouse-management/'
    | '/customer-management/'
    | '/permissions-management/'
    | '/product-categories-management/'
    | '/products-management/'
    | '/purchase-locations-management/'
    | '/reference-documentation/'
    | '/reference-documents-management/'
    | '/roles-management/'
    | '/user-management/'
    | '/ai/example/'
    | '/ai/gemini/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/repair-cases-management/$id'
    | '/payment-pending-repair-cases'
    | '/repair-cases-management'
    | '/accessories-management'
    | '/asc-centers-management'
    | '/central-warehouse-management'
    | '/customer-management'
    | '/permissions-management'
    | '/product-categories-management'
    | '/products-management'
    | '/purchase-locations-management'
    | '/reference-documentation'
    | '/reference-documents-management'
    | '/roles-management'
    | '/user-management'
    | '/ai/example'
    | '/ai/gemini'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_authenticated/'
    | '/_authenticated/(GENERAL)/repair-cases-management'
    | '/_authenticated/(GENERAL)/repair-cases-management/$id'
    | '/_authenticated/(GENERAL)/payment-pending-repair-cases/'
    | '/_authenticated/(GENERAL)/repair-cases-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/'
    | '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/'
    | '/_authenticated/ai/example/'
    | '/_authenticated/ai/gemini/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/(GENERAL)/repair-cases-management': {
      id: '/_authenticated/(GENERAL)/repair-cases-management'
      path: '/repair-cases-management'
      fullPath: '/repair-cases-management'
      preLoaderRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/gemini/': {
      id: '/_authenticated/ai/gemini/'
      path: '/ai/gemini'
      fullPath: '/ai/gemini/'
      preLoaderRoute: typeof AuthenticatedAiGeminiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/example/': {
      id: '/_authenticated/ai/example/'
      path: '/ai/example'
      fullPath: '/ai/example/'
      preLoaderRoute: typeof AuthenticatedAiExampleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/roles-management/'
      path: '/roles-management'
      fullPath: '/roles-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documents-management/'
      path: '/reference-documents-management'
      fullPath: '/reference-documents-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/reference-documentation/'
      path: '/reference-documentation'
      fullPath: '/reference-documentation/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/purchase-locations-management/'
      path: '/purchase-locations-management'
      fullPath: '/purchase-locations-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/products-management/'
      path: '/products-management'
      fullPath: '/products-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/product-categories-management/'
      path: '/product-categories-management'
      fullPath: '/product-categories-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/permissions-management/'
      path: '/permissions-management'
      fullPath: '/permissions-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/customer-management/'
      path: '/customer-management'
      fullPath: '/customer-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/central-warehouse-management/'
      path: '/central-warehouse-management'
      fullPath: '/central-warehouse-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/asc-centers-management/'
      path: '/asc-centers-management'
      fullPath: '/asc-centers-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/': {
      id: '/_authenticated/(SYSTEM-ADMINISTRATION)/accessories-management/'
      path: '/accessories-management'
      fullPath: '/accessories-management/'
      preLoaderRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(GENERAL)/repair-cases-management/': {
      id: '/_authenticated/(GENERAL)/repair-cases-management/'
      path: '/'
      fullPath: '/repair-cases-management/'
      preLoaderRoute: typeof AuthenticatedGENERALRepairCasesManagementIndexRouteImport
      parentRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRoute
    }
    '/_authenticated/(GENERAL)/payment-pending-repair-cases/': {
      id: '/_authenticated/(GENERAL)/payment-pending-repair-cases/'
      path: '/payment-pending-repair-cases'
      fullPath: '/payment-pending-repair-cases/'
      preLoaderRoute: typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(GENERAL)/repair-cases-management/$id': {
      id: '/_authenticated/(GENERAL)/repair-cases-management/$id'
      path: '/$id'
      fullPath: '/repair-cases-management/$id'
      preLoaderRoute: typeof AuthenticatedGENERALRepairCasesManagementIdRouteImport
      parentRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedGENERALRepairCasesManagementRouteRouteChildren {
  AuthenticatedGENERALRepairCasesManagementIdRoute: typeof AuthenticatedGENERALRepairCasesManagementIdRoute
  AuthenticatedGENERALRepairCasesManagementIndexRoute: typeof AuthenticatedGENERALRepairCasesManagementIndexRoute
}

const AuthenticatedGENERALRepairCasesManagementRouteRouteChildren: AuthenticatedGENERALRepairCasesManagementRouteRouteChildren =
  {
    AuthenticatedGENERALRepairCasesManagementIdRoute:
      AuthenticatedGENERALRepairCasesManagementIdRoute,
    AuthenticatedGENERALRepairCasesManagementIndexRoute:
      AuthenticatedGENERALRepairCasesManagementIndexRoute,
  }

const AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren =
  AuthenticatedGENERALRepairCasesManagementRouteRoute._addFileChildren(
    AuthenticatedGENERALRepairCasesManagementRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGENERALRepairCasesManagementRouteRoute: typeof AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren
  AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute: typeof AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute
  AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute: typeof AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute
  AuthenticatedAiExampleIndexRoute: typeof AuthenticatedAiExampleIndexRoute
  AuthenticatedAiGeminiIndexRoute: typeof AuthenticatedAiGeminiIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGENERALRepairCasesManagementRouteRoute:
    AuthenticatedGENERALRepairCasesManagementRouteRouteWithChildren,
  AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute:
    AuthenticatedGENERALPaymentPendingRepairCasesIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONAccessoriesManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONAscCentersManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONCentralWarehouseManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONCustomerManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONPermissionsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONProductCategoriesManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONProductsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONPurchaseLocationsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentationIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONReferenceDocumentsManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONRolesManagementIndexRoute,
  AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute:
    AuthenticatedSYSTEMADMINISTRATIONUserManagementIndexRoute,
  AuthenticatedAiExampleIndexRoute: AuthenticatedAiExampleIndexRoute,
  AuthenticatedAiGeminiIndexRoute: AuthenticatedAiGeminiIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
