export const HTTP_RESPONSE_CODE = {
  OK: 200,
  CREATED: 201,
  MOVED_PERMANENTLY: 301,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

export const HTTP_RESPONSE_MESSAGE = {
  [HTTP_RESPONSE_CODE.OK]: 'OK',
  [HTTP_RESPONSE_CODE.CREATED]: 'Created',
  [HTTP_RESPONSE_CODE.MOVED_PERMANENTLY]: 'Moved Permanently',
  [HTTP_RESPONSE_CODE.BAD_REQUEST]: 'Bad Request',
  [HTTP_RESPONSE_CODE.UNAUTHORIZED]: 'Unauthorized',
  [HTTP_RESPONSE_CODE.FORBIDDEN]: 'Forbidden',
  [HTTP_RESPONSE_CODE.NOT_FOUND]: 'Not Found',
  [HTTP_RESPONSE_CODE.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [HTTP_RESPONSE_CODE.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [HTTP_RESPONSE_CODE.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [HTTP_RESPONSE_CODE.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [HTTP_RESPONSE_CODE.BAD_GATEWAY]: 'Bad Gateway',
  [HTTP_RESPONSE_CODE.SERVICE_UNAVAILABLE]: 'Service Unavailable',
};

export const HTTP_RESPONSE_CODE_LIST = Object.values(HTTP_RESPONSE_CODE);
