ARG PYTHON_IMAGE=python:3.11-slim
ARG PYTHON_DIGEST=sha256:a630a63cdb314e2d138a2fca3e375e319e8568346ffafac5b980f888630ac4f1
FROM ${PYTHON_IMAGE}@${PYTHON_DIGEST}

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src
COPY pyproject.toml /app/pyproject.toml

CMD ["python", "-m", "src.worker"]
