[global]
repo1-type=s3
repo1-path=/servexa-p0a
repo1-s3-endpoint=minio:9000
repo1-s3-region=vn-p0a-1
repo1-s3-bucket=servexa-p0a-backups
repo1-s3-uri-style=path
repo1-storage-verify-tls=n
process-max=2
start-fast=y
log-level-console=info

[p0a]
pg1-path=/var/lib/postgresql/18/docker
pg1-port=5432
pg1-user=servexa_p0a
